# Generated by Django 3.0.7 on 2020-06-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('report_type', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='report/images/')),
            ],
        ),
    ]
