# Generated by Django 3.0.7 on 2020-06-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='read',
        ),
    ]
