# Generated by Django 3.0.7 on 2020-07-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200703_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read',
            name='read_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
