# Generated by Django 3.0.7 on 2020-07-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200703_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read',
            name='read_img',
            field=models.ImageField(upload_to='report/images/'),
        ),
    ]
