# Generated by Django 3.0.7 on 2020-07-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200704_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.FileField(upload_to='report/images/'),
        ),
    ]
