# Generated by Django 3.0.7 on 2020-07-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_report_read_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='read_img',
            field=models.TextField(),
        ),
    ]
