# Generated by Django 3.0.7 on 2020-07-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200707_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='read_img',
        ),
    ]
