# Generated by Django 3.0.7 on 2020-07-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_report_cur_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='cur_date',
            field=models.DateField(),
        ),
    ]
