# Generated by Django 3.0.7 on 2020-07-09 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200709_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='cur_date',
        ),
    ]
