# Generated by Django 3.0.7 on 2020-07-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_report_cur_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='read_img',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
